### ISSUE TITLE
Würde gerne das Repo puplic machen damit ich Domain zukuenfte-gestalten.de bereits einrichten kann

### ISSUE THREAD

**Issue by b-g** [b-g/zukuenfte-gestalten.info#1]
Hi @stephanbogner! 

Würde gerne dieses Repo Puplic machen damit ich die Domain zukuenfte-gestalten.de via Github Pages bereits einrichten kann. Könntest du mir eine leere index.html vorbereiten bzw. die Struktur des Repos Richtung Github Pages vorbereiten? Würde es gerne ab der Woche März 7 einrichten können ... Möglich?

LG,
Bene

PS. bin nächste Woche weg in den Bergen ... eilt also nicht.

**Comment by stephanbogner** [comment]
Ja gerne, Montag 14:00 – 15:00 passt. Wollte eh fragen wann du Zeit hast bzgl. IG 1 :)
